### ISSUE TITLE
Problem while chat selecting

### ISSUE THREAD

**Issue by DockedFerret800** [backmeupplz/randymbot#19]
When i select channel i have error in console.
![image](https://user-images.githubusercontent.com/50877428/105072259-530aba80-5a8e-11eb-828e-be3278774969.png)

Problem in this file https://github.com/backmeupplz/randymbot/blob/master/src/commands/configRaffle.ts

**Comment by backmeupplz** [comment]
Stop creating duplicate issues, please. I cannot reproduce the issue on the production instance. Please, provide the details of your usecase and reopen this issue.

**Comment by DockedFerret800** [comment]
This problem when i use command /configRaffle 
After channel chose i have error

**Comment by DockedFerret800** [comment]
> Stop creating duplicate issues, please. I cannot reproduce the issue on the production instance. Please, provide the details of your usecase and reopen this issue.
This problem when i use command /configRaffle
After channel chose i have error

**Comment by backmeupplz** [comment]
Should be already fixed, thank you for the report.
