### ISSUE TITLE
Dont work raffle msg 

### ISSUE THREAD

**Issue by DockedFerret800** [backmeupplz/randymbot#20]
![image](https://user-images.githubusercontent.com/50877428/105346995-f2df5a00-5bee-11eb-94a8-76c894c2b362.png)
When i want to set raffle msg Nothing happens. I console i dont have any errors.

**Comment by DockedFerret800** [comment]
This problem only in private bot msg.

**Comment by backmeupplz** [comment]
![Screen Shot 2021-01-21 at 6 35 02 AM](https://user-images.githubusercontent.com/3192028/105365168-d02f5000-5bb2-11eb-8294-11201b9f0ef0.png)

Just tested setting up raffle message https://t.me/randymbot. Works well.

**Comment by DockedFerret800** [comment]
> ![Screen Shot 2021-01-21 at 6 35 02 AM](https://user-images.githubusercontent.com/3192028/105365168-d02f5000-5bb2-11eb-8294-11201b9f0ef0.png)
> 
> Just tested setting up raffle message https://t.me/randymbot. Works well.

I have this error, i dont change code.

**Comment by DockedFerret800** [comment]
> ![Screen Shot 2021-01-21 at 6 35 02 AM](https://user-images.githubusercontent.com/3192028/105365168-d02f5000-5bb2-11eb-8294-11201b9f0ef0.png)
> 
> Just tested setting up raffle message https://t.me/randymbot. Works well.

Can you fix this??

**Comment by backmeupplz** [comment]
I can't reproduce it, hence I cannot fix it, but feel free to fix it on your end and submit a pull request :)

**Comment by DockedFerret800** [comment]
> I can't reproduce it, hence I cannot fix it, but feel free to fix it on your end and submit a pull request :)

Can you show me raffleMessage.ts please?

**Comment by backmeupplz** [comment]
Not sure what you mean, it's right here in the repository: https://github.com/backmeupplz/randymbot/blob/master/src/commands/raffleMessage.ts.

**Comment by DockedFerret800** [comment]
> Not sure what you mean, it's right here in the repository: https://github.com/backmeupplz/randymbot/blob/master/src/commands/raffleMessage.ts.

But why i have error but you dont have

**Comment by backmeupplz** [comment]
I don't know.

**Comment by DockedFerret800** [comment]
> I don't know.

This problem only in dm with bot

**Comment by backmeupplz** [comment]
Yep, the screenshot above of how it does work is from dm.

**Comment by DockedFerret800** [comment]
> Yep, the screenshot above of how it does work is from dm.
But bot igonor me when i want to use this command on dm

**Comment by backmeupplz** [comment]
Again, the production instance does not have any issues like this. It is probably the way you set up randy. I can't help you with the self-hosted randy instances if I cannot reproduce the issue.

**Comment by DockedFerret800** [comment]
> Again, the production instance does not have any issues like this. It is probably the way you set up randy. I can't help you with the self-hosted randy instances if I cannot reproduce the issue.

What could be the cause of this problem?

**Comment by backmeupplz** [comment]
@DockedFerret800 maybe bot's username is hardcoded somewhere?

**Comment by DockedFerret800** [comment]
> maybe bot's username is hardcoded somewhere?

In the sense of? I have not changed the code

**Comment by backmeupplz** [comment]
I think I hardcoded it somwhere :) just find it and see if that's the issue

**Comment by backmeupplz** [comment]
well then, the issue is different probably. Anyway, the issue does not affect randymbot production instance so I won't be able to help you

**Comment by DockedFerret800** [comment]
> well then, the issue is different probably. Anyway, the issue does not affect randymbot production instance so I won't be able to help you

But i need to fix this error, but i dont have any problems in console

**Comment by backmeupplz** [comment]
Again, I cannot help you. If you need to fix it, fix it yourselves.

**Comment by DockedFerret800** [comment]
> Again, I cannot help you. If you need to fix it, fix it yourselves.

Why you upload a non-working bot?

**Comment by backmeupplz** [comment]
@DockedFerret800 this software is provided as-is. If you want, you can fix it :) if you have any questions about the bot — feel free to ask them. I'll start removing the unrelated comments contemplating on the open-source nature.

**Comment by DockedFerret800** [comment]
> @DockedFerret800 this software is provided as-is. If you want, you can fix it :) if you have any questions about the bot — feel free to ask them. I'll start removing the unrelated comments contemplating on the open-source nature.

What could be the problem?

**Comment by backmeupplz** [comment]
I don't know. Maybe the bot's username is hardcoded somewhere? Not sure.

**Comment by DockedFerret800** [comment]
> I don't know. Maybe the bot's username is hardcoded somewhere? Not sure.

There is no randymbot in any file

**Comment by backmeupplz** [comment]
Then I don't know what's wrong. Feel free to debug, fix and submit a pull request :) this is how open source works
