### ISSUE TITLE
Bug: unsubscribed winner of raffle 

### ISSUE THREAD

**Issue by AlexMercier** [backmeupplz/randymbot#43]
Hello. 
It seems Bot have a bug.
If I set condition to check user subscribed to channel then bot check subscription only at time when user join to raffle.
But if user will unsubscribe after pressing Participate button then later when raffle is end then when bot will select winner it has no check condition and bot can select unsubscribed user. 
So my suggestion to check that user in target channel when I send command to finish raffle.

**Comment by backmeupplz** [comment]
This is by design

**Comment by AlexMercier** [comment]
> This is by design

А почему так, как это понимать? Условия выигрыша - подписка на канал. Но бот не проверяет подписку в момент финала розыгрыша. Это ведь не правильно. В чем такова суть?
Если в конкурсе указано что надо подписаться на другой канал а пользователь потом оттуда отпишется

**Comment by backmeupplz** [comment]
Feel free to submit a pull request with this feature :)

**Comment by AlexMercier** [comment]
Sorry I don't know typescript=(

**Comment by backmeupplz** [comment]
never late to learn!
