### ISSUE TITLE
[RFE] Keep list of additional winner placeholders if first winner is not eligible

### ISSUE THREAD

**Issue by iranzo** [backmeupplz/randymbot#5]
Would be good to list additional winners in case first is not eligible

**Comment by backmeupplz** [comment]
Can you elaborate, please? You can change number of winners with the /number command :)

**Comment by iranzo** [comment]
If there's only one prize , I do want to have extra winners listed but
sorted in winning order not alphabetically

Regards
Pablo

**Comment by backmeupplz** [comment]
Not sure why they were alphabetized, but I shuffled them one more time just in case ;)
